name: gatsby-integration

on:
  pull_request:
    branches:
      - gatsby-dev

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
      
    steps:
    - name: Checkout projects
      uses: actions/checkout@v2
    - name: Use Node.js @${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
    - run: yarn test:ci
      env:
        CI: test